namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: prod-resource.yaml
