namePrefix: staging-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - includeSelectors: true
    pairs:
      variant: staging
patches:
  - path: staging-resource.yaml
